site_name: Urbano Libre
site_description: Documentation for the integration of Open-Meteo with OTP-Redux
site_author: CodigoTruko

theme:
  custom_dir: overrides
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search
  - i18n:
      default_language: es
      redirect_fallback: true
      languages:
        - locale: es
          name: Español
          default: true
        - locale: en
          name: English

nav:
  - Español:
      - 01-Visión general: es/overview.md
      - 02-Instalación: es/instalacion.md
      - 03-Desarrollo: es/desarrollo.md
      - 04-Pruebas: es/pruebas.md
      - 05-CI/CD: es/ci-cd.md
      - 06-Cambios: es/cambios.md
      - 07-Glosario: es/glosario.md
  - English:
      - 01-Overview: en/overview.md
      - 02-Installation: en/installation.md
      - 03-Development: en/development.md
      - 04-Testing: en/testing.md
      - 05-CI/CD: en/ci-cd.md
      - 06-Changelog: en/changelog.md
      - 07-Glossary: en/glossary.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details


extra:
  generator: false
