site_name: Urbano Libre
site_description: Documentation for the integration of Open-Meteo with OTP-Redux
site_author: CodigoTruko

theme:
  name: material
  language: es
  custom_dir: overrides
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: es
          default: true
          name: Español
          build: true
        - locale: en
          name: English
          build: true

nav:
    - Manual de usuario: manual.md
    - Visión general: overview.md
    - Instalación: installation.md
    - Desarrollo: development.md
    - Limitaciones: limitations.md
    - Pruebas: testing.md
    - CI/CD: ci-cd.md
    - Cambios: changelog.md
    - Glosario: glossary.md


markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

extra:
  generator: false
